### PR TITLE
Use modules

### PR DESCRIPTION
**Pull request by nerochiaro**
Attempting to implement feature #36.

The extension loads fine for me and exporting tilemaps and tilesets works as before.

Tested only with Tiled 1.9

### CODE REVIEW

**Review by eleniums — APPROVED** [review]
I ran some tests and everything seems to work.

**Comment by MikeMnD** [comment]
I've checked the changes and all looks fine to me too!
JS modules are cool addition to Tiled.

**Review by MikeMnD — APPROVED** [review]

**Comment by eleniums** [comment]
Closes #36

**Comment by bjorn** [comment]
So, this does raise the minimum supported Tiled version to 1.8, but that's probably fine by now. Nice work @nerochiaro!

**Pull request merged**
